name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install hidapi dependencies
        # https://github.com/ruabmbua/hidapi-rs/blob/master/.travis.yml
        run: |
          sudo apt-get install libusb-1.0.0-dev libudev-dev libhidapi-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
